# Generated by Django 4.0.1 on 2022-08-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='disponibilidad',
            new_name='completada',
        ),
    ]
