# Generated by Django 3.1.4 on 2022-08-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0002_rename_disponibilidad_tareas_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
