# Generated by Django 3.1.4 on 2022-08-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTareas', '0003_auto_20220801_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tareas',
            name='contenido',
            field=models.CharField(default=1, max_length=150, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
